### PR TITLE
Fix XSS potential

### PR DESCRIPTION
**Pull request by BBcan177**

### CODE REVIEW

**Comment by dougburks** [comment]
Thanks, BBcan177!

**Comment by BBcan177** [comment]
Do you have any concerns with this PR?

**Comment by dougburks** [comment]
No concerns, just haven't had a chance to officially merge it.  It's on the Roadmap so I won't forget about it.

**Comment by BBcan177** [comment]
ok Thanks :)

**Comment by dougburks** [comment]
Added some more htmlspecialchars:
https://github.com/Security-Onion-Solutions/securityonion-web-page/commit/453d527ca092f46a93b99b20d27d28399fa3c6a7

**Comment by dougburks** [comment]
Removed htmlspecialchars altogether and replaced with relative hyperlinks now that Apache is proxying /elsa-query to ELSA port 3154:
#829

**Pull request merged**
